---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: rancher/dapper:v0.6.0
    commands:
      - dapper test
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request

  - name: build
    image: rancher/dapper:v0.6.0
    commands:
      - dapper build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request

  - name: e2e
    image: rancher/dapper:v0.6.0
    commands:
      - dapper e2e
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - promote
      target:
        - e2e
