name: ci
on:
  pull_request:
    types: [labeled]
jobs:
  setup:
    if: ${{ github.event.label.name == 'to-test' }} 
    runs-on: ubuntu-latest
    outputs:
      testcases: ${{ steps.set-testcases.outputs.testcases }}
    steps:
      - id: find-comment
        uses: peter-evans/find-comment@v2.4.0
        with:
          body-includes: /test
      - id: set-testcases
        run: echo "testcases=$(echo ${{ steps.find-comment.outputs.comment-body }} | awk '{print $2}')" >> $GITHUB_OUTPUT
    
  test-job:
    needs: setup
    runs-on: ubuntu-latest
    container: 
      image: rancher/dapper:v0.6.0
      env:
        TESTCASES: ${{ needs.setup.outputs.testcases }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: build
        run: dapper build
      - name: test
        run: dapper test
      - name: e2e
        run: dapper e2e
      
