name: to-test
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  add-test-label:
    if: ${{ github.event.issue.pull_request }} && ${{ startsWith(github.event.comment.body, '/test') }}
    runs-on: ubuntu-latest
    steps:
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/test') }}
        with:
          labels: to-test
      
